media:
  - name: visuals
    label: Visuals Media
    input: media/visuals
    output: media/visuals
  - name: algolab
    label: AlgoLab Media
    input: media/algolab
    output: media/algolab
  - name: installations
    label: Installations Media
    input: media/installations
    output: media/installations

content:
  # Portfolio Projects - Collection of separate files
  - name: projects
    label: Projects
    path: data/projects
    type: collection
    format: json
    filename: "{slug}.json"
    exclude:
      - _index.json
    view:
      fields: [title, category, year]
      primary: title
      sort: [year, title]
      default:
        sort: year
        order: desc
    fields:
      - name: slug
        label: Slug (URL)
        type: string
        required: true
        description: Unique identifier for the URL (e.g. "project-name", no spaces). This also determines the file name.
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Slug must contain only lowercase letters, numbers and hyphens"

      - name: title
        label: Title
        type: string
        required: true
        description: Project name

      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - value: visuals
              label: Visuals
            - value: algolab
              label: AlgoLab
            - value: installations
              label: Installations
        description: Project category

      - name: year
        label: Year
        type: number
        required: true
        description: Year of creation

      - name: description
        label: Description
        type: text
        list: true
        required: true
        description: Project description paragraphs (each item is a paragraph)

      - name: media
        label: Media
        type: object
        list: true
        required: true
        description: Project images and videos
        fields:
          - name: type
            label: Type
            type: select
            required: true
            options:
              values:
                - value: image
                  label: Image
                - value: video
                  label: Video
            default: image

          - name: src
            label: File
            type: image
            required: true
            description: Upload the image or video

          - name: alt
            label: Alt Text
            type: string
            required: true
            description: Image description for accessibility

      - name: links
        label: External Links
        type: object
        description: Optional links to website or repository
        fields:
          - name: site
            label: Website
            type: string
            description: Project website URL

          - name: repo
            label: Repository
            type: string
            description: Repository URL (e.g. GitHub)

      - name: tags
        label: Tags
        type: string
        list: true
        description: Project tags (e.g. "#Touchdesigner, #VJ")

  # About Page
  - name: about
    label: About
    path: data/about.json
    type: file
    format: json
    fields:
      - name: text
        label: Biography
        type: text
        required: true
        description: About section text

  # Contacts
  - name: contacts
    label: Contacts
    path: data/contacts.json
    type: file
    format: json
    fields:
      - name: items
        label: Contacts List
        type: object
        list:
          collapsible:
            collapsed: false
            summary: "{fields.name}"
        fields:
          - name: name
            label: Name
            type: string
            required: true
            description: Contact name (e.g. Instagram, Email)

          - name: slug
            label: Slug
            type: string
            required: true
            description: Unique identifier
            pattern:
              regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
              message: "Slug must contain only lowercase letters, numbers and hyphens"

          - name: url
            label: URL
            type: string
            required: true
            description: Link to profile or email address (mailto:)
