media:
  - name: visuals
    label: Visuals Media
    input: media/visuals
    output: media/visuals
  - name: algolab
    label: AlgoLab Media
    input: media/algolab
    output: media/algolab
  - name: installations
    label: Installations Media
    input: media/installations
    output: media/installations

content:
  # Progetti del Portfolio
  - name: projects
    label: Projects
    path: data/projects.json
    type: file
    format: json
    fields:
      - name: items
        label: Lista Progetti
        type: object
        list:
          collapsible:
            collapsed: false
            summary: "{fields.title} ({fields.category} - {fields.year})"
        fields:
          - name: slug
            label: Slug (URL)
            type: string
            required: true
            description: Identificatore univoco per l'URL (es. "nome-progetto", senza spazi)
            pattern:
              regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
              message: "Lo slug deve contenere solo lettere minuscole, numeri e trattini"

          - name: title
            label: Title
            type: string
            required: true
            description: Nome del progetto

          - name: category
            label: Category
            type: select
            required: true
            options:
              values:
                - value: visuals
                  label: Visuals
                - value: algolab
                  label: AlgoLab
                - value: installations
                  label: Installations
            description: Categoria del progetto

          - name: year
            label: Year
            type: number
            required: true
            description: Anno di realizzazione del progetto

          - name: description
            label: Description
            type: text
            list: true
            required: true
            description: Paragrafi della descrizione del progetto (ogni elemento è un paragrafo)

          - name: media
            label: Media
            type: object
            list: true
            required: true
            description: Immagini e video del progetto
            fields:
              - name: type
                label: Type
                type: select
                required: true
                options:
                  values:
                    - value: image
                      label: Image
                    - value: video
                      label: Video
                default: image

              - name: src
                label: File
                type: image
                required: true
                description: Upload an image or video

              - name: alt
                label: Alternative text
                type: string
                required: true
                description: Alternative text for accessibility

          - name: links
            label: External links
            type: object
            description: Optional links
            fields:
              - name: site
                label: Sito Web
                type: string
                description: URL del sito web del progetto

              - name: repo
                label: Repository
                type: string
                description: URL del repository (es. GitHub)

          - name: tags
            label: Tags
            type: string
            list: true
            description: Tag del progetto (es. "#Touchdesigner, #VJ")

  # Pagina About
  - name: about
    label: About
    path: data/about.json
    type: file
    format: json
    fields:
      - name: text
        label: Biografia
        type: text
        required: true
        description: Testo della sezione About

  # Contatti
  - name: contacts
    label: Contacts
    path: data/contacts.json
    type: file
    format: json
    fields:
      - name: items
        label: Contacts List
        type: object
        list:
          collapsible:
            collapsed: false
            summary: "{fields.name}"
        fields:
          - name: name
            label: Nome
            type: string
            required: true
            description: Name of the contact (e.g. Instagram, Email)

          - name: slug
            label: Slug
            type: string
            required: true
            description: Identificatore univoco
            pattern:
              regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
              message: "The slug must contain only lowercase letters, numbers and hyphens"

          - name: url
            label: URL
            type: string
            required: true
            description: Link to the profile or email address (mailto:)
