media:
  - name: visuals
    label: Visuals Media
    input: media/visuals
    output: media/visuals
  - name: algolab
    label: AlgoLab Media
    input: media/algolab
    output: media/algolab
  - name: installations
    label: Installations Media
    input: media/installations
    output: media/installations

content:
  # Progetti del Portfolio
  - name: projects
    label: Progetti
    path: data/projects.json
    type: file
    format: json
    fields:
      - name: items
        label: Lista Progetti
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{title} ({category} - {year})"
        fields:
          - name: slug
            label: Slug (URL)
            type: string
            required: true
            description: Identificatore univoco per l'URL (es. "nome-progetto", senza spazi)
            pattern:
              regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
              message: "Lo slug deve contenere solo lettere minuscole, numeri e trattini"

          - name: title
            label: Titolo
            type: string
            required: true
            description: Nome del progetto

          - name: category
            label: Categoria
            type: select
            required: true
            options:
              values:
                - value: visuals
                  label: Visuals
                - value: algolab
                  label: AlgoLab
                - value: installations
                  label: Installations
            description: Categoria del progetto

          - name: year
            label: Anno
            type: number
            required: true
            description: Anno di realizzazione del progetto

          - name: description
            label: Descrizione
            type: text
            list: true
            required: true
            description: Paragrafi della descrizione del progetto (ogni elemento è un paragrafo)

          - name: media
            label: Media
            type: object
            list: true
            required: true
            description: Immagini e video del progetto
            fields:
              - name: type
                label: Tipo
                type: select
                required: true
                options:
                  values:
                    - value: image
                      label: Immagine
                    - value: video
                      label: Video
                default: image

              - name: src
                label: File
                type: image
                required: true
                description: Carica l'immagine o il video

              - name: alt
                label: Testo alternativo
                type: string
                required: true
                description: Descrizione dell'immagine per accessibilità

          - name: links
            label: Link esterni
            type: object
            description: Link opzionali al sito web o repository
            fields:
              - name: site
                label: Sito Web
                type: string
                description: URL del sito web del progetto

              - name: repo
                label: Repository
                type: string
                description: URL del repository (es. GitHub)

          - name: tags
            label: Tags
            type: string
            list: true
            description: Tag del progetto (es. "#Touchdesigner, #VJ")

  # Pagina About
  - name: about
    label: About
    path: data/about.json
    type: file
    format: json
    fields:
      - name: text
        label: Biografia
        type: text
        required: true
        description: Testo della sezione About

  # Contatti
  - name: contacts
    label: Contatti
    path: data/contacts.json
    type: file
    format: json
    fields:
      - name: items
        label: Lista Contatti
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{name}"
        fields:
          - name: name
            label: Nome
            type: string
            required: true
            description: Nome del contatto (es. Instagram, Email)

          - name: slug
            label: Slug
            type: string
            required: true
            description: Identificatore univoco
            pattern:
              regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
              message: "Lo slug deve contenere solo lettere minuscole, numeri e trattini"

          - name: url
            label: URL
            type: string
            required: true
            description: Link al profilo o indirizzo email (mailto:)
